project_name: unbox
builds:
  - main: ../cmd/unbox/
    binary: unbox
    id: default
    env: [CGO_ENABLED=0]
    goos:
      - android
    goarch:
      - arm64
    

nfpms:
  - maintainer: aceberg <aceberg_a@proton.me>
    description: tool to convert a file with VLESS links to a full sing-box config
    homepage: https://github.com/aceberg/unbox
    license: MIT
    section: utils
    formats:
    - termux.deb

archives:
  - wrap_in_directory: true